import { useCallback, useEffect, useMemo, useState } from 'react'
import { FiCheck, FiChevronRight, FiCopy, FiExternalLink, FiLink, FiLogIn, FiLogOut, FiMinus, FiPackage, FiPlus, FiRefreshCw, FiSend, FiTruck, FiUserPlus, FiX } from 'react-icons/fi'
import { supabase } from '../lib/supabase'
import './sticker-balance.css'

const fmt = n => new Intl.NumberFormat('en-NG').format(Number(n || 0))
const money = n => new Intl.NumberFormat('en-NG', {style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n || 0))
const phone = s => String(s || '').replace(/[^0-9+]/g,'')
const codeFromPath = () => { const m = window.location.pathname.match(/^\/b\/([^/]+)$/); return m ? decodeURIComponent(m[1]) : '' }
const linkFor = code => window.location.origin + '/b/' + encodeURIComponent(code)

function Logo(){return <div className="sb-logo"><b className="sb-logo-mark">S</b><div><strong>Sticker Balance</strong><span>Sleekblue Media Houz</span></div></div>}
function Btn({children,icon:Icon,secondary=false,...p}){return <button className={'sb-btn '+(secondary?'secondary':'')} {...p}>{Icon&&<Icon/>}{children}</button>}
function Modal({title,sub,onClose,children}){return <div className="sb-modal-bg" onMouseDown={onClose}><div className="sb-modal" onMouseDown={e=>e.stopPropagation()}><div className="sb-modal-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div><button className="sb-x" onClick={onClose}><FiX/></button></div>{children}</div></div>}

function StaffLogin({done}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('')
 const submit=async e=>{e.preventDefault();setBusy(true);setErr('');const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error)return setErr('Email or password is not correct.');done(data.session)}
 return <main className="sb-login"><div className="sb-login-card"><Logo/><h1>Sticker Balance</h1><p>Staff sign in. Customers use their permanent link.</p><form className="sb-form" onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{err&&<div className="sb-error">{err}</div>}<Btn icon={FiLogIn} disabled={busy}>{busy?'Signing in…':'Sign in'}</Btn></form></div></main>
}

function PhoneGate({code,onLogin}){
 const [value,setValue]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('')
 const submit=async e=>{e.preventDefault();setBusy(true);setErr('');const {data,error}=await supabase.rpc('sb_customer_snapshot',{p_access_code:code,p_phone:phone(value)});setBusy(false);if(error||!data)return setErr('That phone number does not match this business.');onLogin(phone(value),data)}
 return <main className="sb-customer"><div className="sb-customer-shell sb-gate"><Logo/><div className="sb-empty"><div className="sb-big-icon"><FiPackage/></div><h1>Your business page</h1><p>Enter the phone number Sleekblue has for this business.</p><form className="sb-form" onSubmit={submit}><label>Phone number<input inputMode="tel" value={value} onChange={e=>setValue(e.target.value)} placeholder="08012345678" required/></label>{err&&<div className="sb-error">{err}</div>}<Btn icon={FiLogIn} disabled={busy}>{busy?'Checking…':'Open my page'}</Btn></form><small className="sb-help">The same link works on another phone too.</small></div></div></main>
}

function CustomerPortal({code}){
 const key='sb-phone-'+code
 const [customerPhone,setCustomerPhone]=useState(()=>sessionStorage.getItem(key)||''),[data,setData]=useState(null),[loading,setLoading]=useState(Boolean(sessionStorage.getItem(key))),[modal,setModal]=useState(''),[product,setProduct]=useState(null),[qty,setQty]=useState(''),[sale,setSale]=useState({product_name:'',quantity:'1',amount:''}),[err,setErr]=useState(''),[msg,setMsg]=useState('')
 const load=useCallback(async p=>{setLoading(true);const {data:d,error}=await supabase.rpc('sb_customer_snapshot',{p_access_code:code,p_phone:p});setLoading(false);if(error||!d){sessionStorage.removeItem(key);setCustomerPhone('');setData(null);return setErr('Your access could not be verified.')}setData(d);setErr('')},[code,key])
 useEffect(()=>{if(customerPhone)load(customerPhone)},[customerPhone,load])
 const login=(p,d)=>{sessionStorage.setItem(key,p);setCustomerPhone(p);setData(d)}
 const saveSale=async e=>{e.preventDefault();const q=Number(sale.quantity),a=Number(sale.amount);if(!sale.product_name.trim()||q<=0||a<0)return setErr('Enter the product, quantity and amount.');const {error}=await supabase.rpc('sb_record_customer_sale',{p_access_code:code,p_phone:customerPhone,p_product_name:sale.product_name.trim(),p_quantity:q,p_amount:a});if(error)return setErr(error.message||'Could not save sale.');setSale({product_name:'',quantity:'1',amount:''});setModal('');setMsg('Sale saved.');load(customerPhone)}
 const saveUsage=async e=>{e.preventDefault();const n=Number(qty);if(!product||n<1)return setErr('Enter a valid quantity.');const {error}=await supabase.rpc('sb_record_customer_usage',{p_access_code:code,p_phone:customerPhone,p_product_id:product.id,p_quantity:n});if(error)return setErr(error.message||'Could not save usage.');setQty('');setModal('');setMsg(fmt(n)+' stickers used.');load(customerPhone)}
 if(!customerPhone&&!data)return <PhoneGate code={code} onLogin={login}/>
 if(loading&&!data)return <main className="sb-customer"><div className="sb-loading"><FiRefreshCw className="spin"/>Loading your page…</div></main>
 if(!data)return <PhoneGate code={code} onLogin={login}/>
 const c=data.customer,products=data.products||[],sales=data.sales||[],movements=data.movements||[]
 return <main className="sb-customer"><div className="sb-customer-shell">
  <div className="sb-customer-top"><Logo/><button className="sb-linkout" onClick={()=>{sessionStorage.removeItem(key);setCustomerPhone('');setData(null)}}>Close</button></div>
  <section className="sb-welcome"><div><small>YOUR BUSINESS</small><h1>{c.business_name}</h1>{c.contact_name&&<p>Hello {c.contact_name}</p>}</div><b className="good">Connected</b></section>
  {msg&&<div className="sb-success sb-top-message">✓ {msg}</div>}
  <div className="sb-customer-actions"><Btn icon={FiPlus} onClick={()=>{setErr('');setModal('sale')}}>Record Sale</Btn><Btn secondary icon={FiPackage} onClick={()=>{setErr('');setProduct(products[0]||null);setQty('');setModal('usage')}}>Record Sticker Use</Btn></div>
  <section className="sb-section-card"><div className="sb-section-head"><h2>Sticker Balance</h2><p>Supplied, used and remaining.</p></div>{products.length?products.map(p=><div className="sb-product" key={p.id}><div className="sb-product-icon"><FiPackage/></div><div className="sb-product-main"><b>{p.name}</b><span>{fmt(p.delivered)} received · {fmt(p.used)} used</span></div><div className={'sb-product-balance '+(Number(p.remaining)<=Number(p.reorder_level)?'danger':'good')}><strong>{fmt(p.remaining)}</strong><small>left</small></div></div>):<div className="sb-empty-inline">No sticker products have been added yet.</div>}</section>
  <section className="sb-section-card"><div className="sb-section-head"><h2>Recent Sales</h2><p>Your latest sales.</p></div>{sales.length?sales.slice(0,12).map(s=><div className="sb-history-row" key={s.id}><div><b>{s.product_name} · {fmt(s.quantity)}</b><span>{new Date(s.sold_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</span></div><strong>{money(s.amount)}</strong></div>):<div className="sb-empty-inline">No sales recorded yet.</div>}</section>
  <section className="sb-section-card"><div className="sb-section-head"><h2>Sticker Activity</h2><p>Recent deliveries and usage.</p></div>{movements.length?movements.slice(0,12).map(m=><div className="sb-history-row" key={m.id}><div><b>{m.movement_type==='delivery'?'+':''}{fmt(m.quantity)} {m.product_name}</b><span>{m.movement_type==='delivery'?'Received':'Used'} · {new Date(m.created_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</span></div><strong>{m.movement_type==='delivery'?'Received':'Used'}</strong></div>):<div className="sb-empty-inline">No sticker activity yet.</div>}</section>
  <footer>Need stickers? Contact Sleekblue Media Houz.</footer>
 </div>
 {modal==='sale'&&<Modal title="Record Sale" sub="Enter what you sold today." onClose={()=>setModal('')}><form className="sb-form" onSubmit={saveSale}><label>What did you sell?<input autoFocus value={sale.product_name} onChange={e=>setSale({...sale,product_name:e.target.value})} placeholder="Zobo" required/></label><label>Quantity<input inputMode="decimal" value={sale.quantity} onChange={e=>setSale({...sale,quantity:e.target.value})} required/></label><label>Amount received<input inputMode="decimal" value={sale.amount} onChange={e=>setSale({...sale,amount:e.target.value})} placeholder="5000" required/></label>{err&&<div className="sb-error">{err}</div>}<Btn icon={FiCheck}>Save Sale</Btn></form></Modal>}
 {modal==='usage'&&<Modal title="Record Sticker Use" sub="Choose the sticker and enter how many." onClose={()=>setModal('')}><form className="sb-form" onSubmit={saveUsage}><label>Sticker product<select value={product?.id||''} onChange={e=>setProduct(products.find(p=>p.id===e.target.value)||null)} required><option value="">Choose sticker</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {fmt(p.remaining)} left</option>)}</select></label><div className="sb-big-number"><small>STICKERS USED</small><input autoFocus inputMode="numeric" value={qty} onChange={e=>setQty(e.target.value.replace(/\D/g,'').slice(0,8))} placeholder="0"/></div>{err&&<div className="sb-error">{err}</div>}<Btn icon={FiCheck}>Save Usage</Btn></form></Modal>}
 </main>
}

function Admin({session,signOut}){
 const [profile,setProfile]=useState(null),[data,setData]=useState({customers:[]}),[selectedId,setSelectedId]=useState(null),[selectedProduct,setSelectedProduct]=useState(null),[modal,setModal]=useState(''),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 const selected=useMemo(()=>data.customers.find(c=>c.id===selectedId)||null,[data.customers,selectedId])
 const load=useCallback(async()=>{setLoading(true);const [{data:p},{data:d,error}]=await Promise.all([supabase.from('profiles').select('full_name,role').eq('id',session.user.id).maybeSingle(),supabase.rpc('sb_get_admin_snapshot')]);if(p)setProfile(p);if(error)setNotice(error.message);if(d)setData(d);setSelectedId(id=>id||d?.customers?.[0]?.id||null);setLoading(false)},[session.user.id])
 useEffect(()=>{load()},[load])
 const say=m=>{setNotice(m);setTimeout(()=>setNotice(''),3500)}
 const addCustomer=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {data:r,error}=await supabase.rpc('sb_create_customer',{p_business_name:String(f.get('business_name')),p_customer_name:String(f.get('customer_name')),p_phone:phone(String(f.get('phone')))});if(error)return say(error.message);setModal('');await load();setSelectedId(r.id);say('Customer created. Permanent link ready.')}
 const addProduct=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('sb_add_product',{p_customer_id:selected.id,p_name:String(f.get('name')),p_reorder_level:Number(f.get('reorder_level')||500),p_warning_level:Number(f.get('warning_level')||1000)});if(error)return say(error.message);setModal('');await load();say('Sticker product added.')}
 const movement=async(type,e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('sb_record_movement',{p_product_id:String(f.get('product_id')),p_type:type,p_quantity:Number(f.get('quantity')),p_note:String(f.get('note')||'')||null});if(error)return say(error.message);setModal('');await load();say(type==='delivery'?'Delivery added.':'Usage recorded.')}
 const link=selected?.access_code?linkFor(selected.access_code):''
 const list=data.customers.filter(c=>(c.business_name+' '+c.customer_code+' '+(c.phone||'')).toLowerCase().includes(search.toLowerCase()))
 if(profile&&profile.role!=='admin')return <main className="sb-login"><div className="sb-login-card"><Logo/><h1>Staff only</h1><p>Customers use the permanent link sent to them.</p><Btn secondary icon={FiLogOut} onClick={signOut}>Sign out</Btn></div></main>
 return <main className="sb-admin"><aside><Logo/><button className="sb-nav active"><FiPackage/>Sticker Balance</button><button className="sb-nav" onClick={signOut}><FiLogOut/>Sign out</button></aside><section className="sb-main">
  <header><small>SLEEKBLUE</small><h1>Sticker Balance</h1><p>Customers, sticker stock, sales and reorder alerts.</p></header>
  {notice&&<div className="sb-toast">{notice}</div>}
  <div className="sb-stats"><div><span>Customers</span><b>{data.customers.length}</b></div><div><span>Sticker units left</span><b>{fmt(data.customers.reduce((n,c)=>n+c.products.reduce((x,p)=>x+Number(p.remaining||0),0),0))}</b></div><div><span>Low stock</span><b>{data.customers.reduce((n,c)=>n+c.products.filter(p=>Number(p.remaining)<=Number(p.reorder_level)).length,0)}</b></div></div>
  <div className="sb-toolbar"><input placeholder="Search business, phone or code" value={search} onChange={e=>setSearch(e.target.value)}/><Btn icon={FiUserPlus} onClick={()=>setModal('customer')}>Add Customer</Btn></div>
  {loading?<div className="sb-loading"><FiRefreshCw className="spin"/>Loading…</div>:<div className="sb-grid"><div className="sb-list"><h2>Customers <span>{list.length}</span></h2>{list.map(c=><button key={c.id} className={selectedId===c.id?'selected':''} onClick={()=>setSelectedId(c.id)}><i>{c.business_name.slice(0,1).toUpperCase()}</i><div><b>{c.business_name}</b><span>{c.phone||'No phone'} · {c.customer_code}</span></div><strong>{fmt(c.products.reduce((n,p)=>n+Number(p.remaining||0),0))}<small>{c.products.some(p=>Number(p.remaining)<=Number(p.reorder_level))?'Low stock':'OK'}</small></strong><FiChevronRight/></button>)}</div>
  {selected?<div className="sb-detail"><div className="sb-detail-top"><div><small>CUSTOMER</small><h2>{selected.business_name}</h2><p>{selected.contact_name||'Customer'} · {selected.phone} · {selected.customer_code}</p></div><div><Btn secondary icon={FiLink} onClick={()=>{navigator.clipboard?.writeText(link);say('Permanent link copied.')}}>Copy Link</Btn><Btn icon={FiPlus} onClick={()=>setModal('product')}>Add Sticker</Btn></div></div>
   <div className="sb-link"><div><FiLink/><b>Permanent customer link</b><span>This link stays the same. Send it again whenever needed.</span></div><div><button onClick={()=>navigator.clipboard?.writeText(link).then(()=>say('Link copied.'))}><FiCopy/>Copy</button><a href={'https://wa.me/?text='+encodeURIComponent('Hello '+selected.business_name+', this is your permanent Sticker Balance link: '+link)} target="_blank" rel="noreferrer"><FiSend/>WhatsApp</a><a href={link} target="_blank" rel="noreferrer"><FiExternalLink/>Open</a></div></div>
   <div className="sb-product-grid">{selected.products.map(p=>{const low=Number(p.remaining)<=Number(p.reorder_level);return <div className={'sb-product-card '+(low?'low':'')} key={p.id}><div><small>STICKER</small><h3>{p.name}</h3></div><strong>{fmt(p.remaining)}</strong><span>{fmt(p.delivered)} received · {fmt(p.used)} used</span><b>{low?'LOW STOCK':'OK'}</b><div className="sb-card-actions"><Btn secondary icon={FiTruck} onClick={()=>{setSelectedProduct(p);setModal('delivery')}}>Add Delivery</Btn><Btn secondary icon={FiMinus} onClick={()=>{setSelectedProduct(p);setModal('usage')}}>Record Use</Btn></div></div>})}</div>
   {!selected.products.length&&<div className="sb-empty-inline">No sticker products yet. Add the first one above.</div>}
  </div>:<div className="sb-detail empty"><h2>Choose a customer</h2><p>You will see their permanent link and sticker products here.</p></div>}</div>}
 </section>
 {modal==='customer'&&<Modal title="Add Customer" sub="Only three details are needed." onClose={()=>setModal('')}><form className="sb-form" onSubmit={addCustomer}><label>Customer name<input name="customer_name" autoFocus required/></label><label>Business name<input name="business_name" required/></label><label>Phone number<input name="phone" inputMode="tel" placeholder="08012345678" required/></label><div className="sb-note">A permanent link is created automatically.</div><Btn icon={FiUserPlus}>Create Customer</Btn></form></Modal>}
 {modal==='product'&&<Modal title="Add Sticker Product" sub={selected?.business_name} onClose={()=>setModal('')}><form className="sb-form" onSubmit={addProduct}><label>Sticker / product name<input name="name" autoFocus placeholder="Zobo" required/></label><label>Low-stock alert level<input name="reorder_level" type="number" min="0" defaultValue="500" required/></label><label>Warning level<input name="warning_level" type="number" min="0" defaultValue="1000" required/></label><Btn icon={FiPlus}>Add Sticker Product</Btn></form></Modal>}
 {modal==='delivery'&&<Modal title="Add Delivery" sub={selected?.business_name} onClose={()=>setModal('')}><form className="sb-form" onSubmit={e=>movement('delivery',e)}><input type="hidden" name="product_id" value={selectedProduct?.id||''}/><div className="sb-note">{selectedProduct?.name} — stickers supplied to this customer.</div><div className="sb-big-number"><small>STICKERS RECEIVED</small><input name="quantity" autoFocus inputMode="numeric" placeholder="0" required/></div><label>Note<input name="note" placeholder="Optional"/></label><Btn icon={FiTruck}>Save Delivery</Btn></form></Modal>}
 {modal==='usage'&&<Modal title="Record Sticker Use" sub={selected?.business_name} onClose={()=>setModal('')}><form className="sb-form" onSubmit={e=>movement('usage',e)}><input type="hidden" name="product_id" value={selectedProduct?.id||''}/><div className="sb-note">{selectedProduct?.name} — record stickers used.</div><div className="sb-big-number"><small>STICKERS USED</small><input name="quantity" autoFocus inputMode="numeric" placeholder="0" required/></div><Btn icon={FiCheck}>Save Usage</Btn></form></Modal>}
 </main>
}

export default function StickerBalancePage(){
 const code=codeFromPath(),[session,setSession]=useState(null),[ready,setReady]=useState(Boolean(code))
 useEffect(()=>{if(code)return;let ok=true;supabase.auth.getSession().then(({data})=>{if(ok){setSession(data.session);setReady(true)}});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{ok=false;l?.subscription?.unsubscribe()}},[code])
 const signOut=async()=>{await supabase.auth.signOut();setSession(null)}
 if(code)return <CustomerPortal code={code}/>
 if(!ready)return <main className="sb-login"><div className="sb-loading"><FiRefreshCw className="spin"/></div></main>
 return session?<Admin session={session} signOut={signOut}/>:<StaffLogin done={setSession}/>
}
